In [2]:
import numpy as np
q1 = np.array([[200,220,250],
               [150,180,210],
               [300,330,360]])

q2 = np.array([[209,239,259],
               [155,192,222],
               [310,340,375]])

In [3]:
q1+q2

array([[409, 459, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [4]:
q2-q1

array([[ 9, 19,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [6]:
# i want in percentage

(q2-q1)*100/q1

array([[4.5       , 8.63636364, 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])