NUMPY is a powerful library used for data analysis and machine learinig and scientific computing

In [ ]:
#Numpy use -1

#1.Numpy array takes less memroy as compared to python lists.
import numpy as np

l = list(range(100))
l[:5]


[0, 1, 2, 3, 4]

In [18]:
a = np.arange(100)
print(a[:5])

[0 1 2 3 4]


In [19]:
import sys
print("The List size",sys.getsizeof(l))
print("The array size",sys.getsizeof(a))

The List size 856
The array size 512


2.Numpy array stores elements in contigous manner whereas list cannot store properly it sotres randomly in memory

3.NumPy aray executes faster than list

In [28]:
import time
size = 100000
l = list(range(size))
l2 = list(range(size))

start_time = time.time()
c = [l+l2 for l,l2 in zip(l,l2)]

end_time = time.time()

print("Python will takes time : ",end_time-start_time)


Python will takes time :  0.02155470848083496


In [30]:
import numpy as np
import time
size = 100000
l = np.arange(size)
l2 = np.arange(size)

start_time = time.time()
c = l+l2

end_time = time.time()

print("Numpy aray takes time : ",end_time-start_time)


Numpy aray takes time :  0.0010139942169189453


Convinient list with built-in functions

In [31]:
rev_q1 = np.array([12,34,51])
rev_q1

array([12, 34, 51])

In [36]:
rev = np.array([[1,2,3],[5,6,4]])

rev[0,0] = 5
rev


array([[5, 2, 3],
       [5, 6, 4]])

In [ ]:
# data Type
rev = np.array([1,2,3,4],dtype='float64')

rev.dtype


dtype('float64')

In [ ]:
# No.of bytes
rev.itemsize

8

In [48]:
#shape
rev.shape

(4,)

In [ ]:
# n dimensions
rev.ndim

1

In [51]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [57]:
rev = np.array([[1,2,3,4,5],[6,43,2,6,22]])

rev.flatten()

array([ 1,  2,  3,  4,  5,  6, 43,  2,  6, 22])

In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
rev = np.array([[1,2,3,4],[56,87,98,12]])

rev

array([[ 1,  2,  3,  4],
       [56, 87, 98, 12]])

In [79]:
rev[0][0:].sum()

10